volumes:
  sqlserver_data:
  aspnet_data:
  
services:
  lawfirmcms:
    image: paraon/law-firm-cms:latest
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=LawFirmCMS;Trusted_Connection=False;TrustServerCertificate=True;MultipleActiveResultSets=true;User Id=sa;Password=password123sdJwnwlk@;
    volumes:
      - aspnet_data:/root/.aspnet
    ports:
      - 8080:8080
      - 8081:8081
    restart: always
    depends_on:
      sqlserver:
        condition: service_healthy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=password123sdJwnwlk@
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P password123sdJwnwlk@ -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server:2019-latest
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -C -S sqlserver -U sa -P password123sdJwnwlk@ -d master -i docker-entrypoint-initdb.d/init.sql;
      echo "All done!";
      '